<?php
// module/Security/view/security/user/edit.phtml:

$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'album',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
echo $this->form($form, 'horizontal');
//echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('name'));
//echo $this->formRow($form->get('email'));
//echo $this->formRow($form->get('password'));
//echo $this->formRow($form->get('phone_number'));
//echo $this->formRow($form->get('address'));
//
//echo $this->formSubmit($form->get('submit'));
//echo $this->form()->closeTag();