<?php
// module/Album/view/album/album/index.phtml:

$title = 'Users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('users', array('action'=>'add'));?>">Add new user</a>
</p>
<?php echo $this->flashMessage() ?>

<div class="container" style="margin-top: 10px">
    <div id="example_wrapper" class="dataTables_wrapper form-inline" role="grid">
        <div class="row">
        <div class="span6">
            <div id="example_length" class="dataTables_length">
                <label>
                    <select size="1" name="example_length" aria-controls="example">
                        <option value="10" selected="selected">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    records per page
                </label>
            </div>
        </div>
        <div class="span6">
            <div class="dataTables_filter" id="example_filter">
                <label>
                    Search:
                    <input type="text" aria-controls="example"/>
                </label>
            </div>
        </div>
    </div>
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
                <thead>
                        <tr>
                               
                                <th class="sorting_desc" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" colspan="1" style="width: 167px;" aria-sort="descending" aria-label="Rendering engine: activate to sort column ascending">Id</th>
                                <th class="sorting_desc" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" 
                                    colspan="1" style="width: 167px;" aria-sort="descending" 
                                    aria-label="Rendering engine: activate to sort column ascending">
                                    Name
                                </th>
                                 <th class="sorting_desc" role="columnheader" tabindex="0" aria-controls="example" rowspan="1" 
                                    colspan="1" style="width: 167px;" aria-sort="descending" 
                                    aria-label="Rendering engine: activate to sort column ascending">
                                    Email
                                </th>
                                <th>Action</th>
                        </tr>
                </thead>
                <tbody>
                    <?php
                    
                        foreach ($users as $user) : ?>
                        <tr class="odd gradeX">
                            <td><?php echo $this->escapeHtml($user->id);?></td>
                            <td><?php echo $this->escapeHtml($user->name);?></td>
                            <td><?php echo $this->escapeHtml($user->email);?></td>
                            <td>
                                 <a href="<?php echo $this->url('users',
                                    array('action'=>'edit', 'id' => $user->id));?>">Edit</a>
                            <a href="<?php echo $this->url('users',
                                    array('action'=>'delete', 'id' => $user->id));?>">Delete</a>
                            </td>
                        </tr>
                   <?php endforeach; ?>
                </tbody>
        </table>
        <div class="row">
            <div class="span6">
                <div class="dataTables_info" id="example_info">Showing 1 to 10 of 57 entries</div>
            </div>
            <div class="span6">
                <div class="dataTables_paginate paging_bootstrap pagination">
                    <ul>
                      <li class="prev disabled"><a href="#">Prev</a></li>
                      <li  class="active"><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li class="next"><a href="#">Next</a></li>
                    </ul>
              </div>
            </div>
            
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').dataTable( {
            "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>"
        } );
        
        $.extend( $.fn.dataTableExt.oStdClasses, {
            "sWrapper": "dataTables_wrapper form-inline"
        } );
        
    });
</script>
                