<?php
// module/Album/view/album/album/index.phtml:

$title = 'Migrations';
$this->headTitle($title);
?>
<?php echo $this->flashMessage() ?>

<div class="row">
    <div class="col-lg-12">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->url('app-config') ?>"><i class="icon-dashboard"></i> Dashboard</a></li>
            <li class="active"><i class="icon-file-alt"></i> Migrations</li>
        </ol>
    </div>
</div><!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped table-bordered" id="data-table">
            <thead>
                <tr>
                    <th>Version</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($migrations as $migration) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($migration->getVersion()); ?></td>
                        <td>Remove</td>
                    </tr>
                <?php endforeach; ?>
                <?php if (!count($migrations)): ?>
                    <tr>
                        <td colspan="2">No migrations executed...</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>