<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->flashMessage() ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

$options = array( 'fieldsets' => array('fs-1'));

echo $this->formTwb()->openTag($form, 'vertical');
//
//var_dump($form->get('title'));
//echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRowTwb($form->get('title'));
echo $this->formRowTwb($form->get('artist'));
$actions    = array(
    $form->get('submit'),
);
echo $this->formActionsTwb($actions, 'vertical', array('submit' => array('class' => 'btn-primary')));
echo $this->formTwb()->closeTag();