<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
</p>
<?php echo $this->flashMessage() ?>

<div class="container" >
    

        <table class="table table-striped table-bordered" id="data-table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Artist</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($albums as $user) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($user->title);?></td>
                        <td><?php echo $this->escapeHtml($user->artist);?></td>
                        <td>
                             <a href="<?php echo $this->url('album',
                                array('action'=>'edit', 'id' => $user->id));?>">Edit</a>
                        <a href="<?php echo $this->url('album',
                                array('action'=>'delete', 'id' => $user->id));?>">Delete</a>
                        </td>
                    </tr>
               <?php endforeach; ?>
            </tbody>
        </table>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#data-table').dataTable();
    });
</script>
                