<h1>Sign In</h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->get('identity')->setAttribute('class','form-control');
$form->get('credential')->setAttribute('class','form-control');
$form->get('submit')->setAttribute('class','btn btn-success');
?>
<div class="row">
<?php echo $this->form()->openTag($form) ?>
<div class="col-md-4">
        <?php echo $this->formElementErrors($form->get('identity')) ?>
    <dl>
        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
        <?php endif ?>
    </dl>
    <div class="clearfix"><?php echo $this->formButton($form->get('submit')) ?></div>
</div>

<?php echo $this->form()->closeTag() ?>
</div>
<?php if ($this->enableRegistration) : ?>
Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
<?php endif; ?>
